// Type badge colors — vivid on light backgrounds
export const typeColors: Record<string, string> = {
  Normal: "bg-zinc-400",
  Fire: "bg-orange-500",
  Water: "bg-blue-500",
  Electric: "bg-amber-500",
  Grass: "bg-emerald-500",
  Ice: "bg-cyan-500",
  Fighting: "bg-red-600",
  Poison: "bg-purple-500",
  Ground: "bg-amber-600",
  Flying: "bg-indigo-400",
  Psychic: "bg-pink-500",
  Bug: "bg-lime-500",
  Rock: "bg-yellow-700",
  Ghost: "bg-purple-600",
  Dragon: "bg-violet-500",
  Dark: "bg-zinc-600",
  Steel: "bg-slate-400",
  Fairy: "bg-pink-400",
};

// Hex values for programmatic use (borders, glows, gradients)
export const typeHex: Record<string, string> = {
  Normal: "#a1a1aa",
  Fire: "#f97316",
  Water: "#3b82f6",
  Electric: "#facc15",
  Grass: "#10b981",
  Ice: "#22d3ee",
  Fighting: "#dc2626",
  Poison: "#a855f7",
  Ground: "#d97706",
  Flying: "#818cf8",
  Psychic: "#ec4899",
  Bug: "#84cc16",
  Rock: "#a16207",
  Ghost: "#9333ea",
  Dragon: "#8b5cf6",
  Dark: "#52525b",
  Steel: "#94a3b8",
  Fairy: "#f472b6",
};

// Card image background — soft pastel tints
export const typeBgGradients: Record<string, string> = {
  Normal: "from-zinc-50 to-stone-100",
  Fire: "from-orange-50 to-amber-50",
  Water: "from-blue-50 to-sky-50",
  Electric: "from-yellow-50 to-amber-50",
  Grass: "from-emerald-50 to-green-50",
  Ice: "from-cyan-50 to-sky-50",
  Fighting: "from-red-50 to-rose-50",
  Poison: "from-purple-50 to-violet-50",
  Ground: "from-amber-50 to-yellow-50",
  Flying: "from-indigo-50 to-blue-50",
  Psychic: "from-pink-50 to-fuchsia-50",
  Bug: "from-lime-50 to-green-50",
  Rock: "from-yellow-50 to-amber-50",
  Ghost: "from-purple-50 to-indigo-50",
  Dragon: "from-violet-50 to-purple-50",
  Dark: "from-zinc-100 to-stone-100",
  Steel: "from-slate-50 to-zinc-50",
  Fairy: "from-pink-50 to-rose-50",
};

// Rich hero gradients for detail page
export const typeHeroGradients: Record<string, string> = {
  Normal: "from-zinc-100 via-stone-50 to-transparent",
  Fire: "from-orange-100 via-amber-50 to-transparent",
  Water: "from-blue-100 via-sky-50 to-transparent",
  Electric: "from-yellow-100 via-amber-50 to-transparent",
  Grass: "from-emerald-100 via-green-50 to-transparent",
  Ice: "from-cyan-100 via-sky-50 to-transparent",
  Fighting: "from-red-100 via-rose-50 to-transparent",
  Poison: "from-purple-100 via-violet-50 to-transparent",
  Ground: "from-amber-100 via-yellow-50 to-transparent",
  Flying: "from-indigo-100 via-blue-50 to-transparent",
  Psychic: "from-pink-100 via-fuchsia-50 to-transparent",
  Bug: "from-lime-100 via-green-50 to-transparent",
  Rock: "from-yellow-100 via-amber-50 to-transparent",
  Ghost: "from-purple-100 via-indigo-50 to-transparent",
  Dragon: "from-violet-100 via-purple-50 to-transparent",
  Dark: "from-zinc-200 via-stone-50 to-transparent",
  Steel: "from-slate-100 via-zinc-50 to-transparent",
  Fairy: "from-pink-100 via-rose-50 to-transparent",
};
